# Copyright 2010-present Basho Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from six import *
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_yokozuna.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13riak_yokozuna.proto\"?\n\x10RpbYokozunaIndex\x12\x0c\n\x04name\x18\x01 \x02(\x0c\x12\x0e\n\x06schema\x18\x02 \x01(\x0c\x12\r\n\x05n_val\x18\x03 \x01(\r\"&\n\x16RpbYokozunaIndexGetReq\x12\x0c\n\x04name\x18\x01 \x01(\x0c\";\n\x17RpbYokozunaIndexGetResp\x12 \n\x05index\x18\x01 \x03(\x0b\x32\x11.RpbYokozunaIndex\"K\n\x16RpbYokozunaIndexPutReq\x12 \n\x05index\x18\x01 \x02(\x0b\x32\x11.RpbYokozunaIndex\x12\x0f\n\x07timeout\x18\x02 \x01(\r\")\n\x19RpbYokozunaIndexDeleteReq\x12\x0c\n\x04name\x18\x01 \x02(\x0c\"2\n\x11RpbYokozunaSchema\x12\x0c\n\x04name\x18\x01 \x02(\x0c\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"=\n\x17RpbYokozunaSchemaPutReq\x12\"\n\x06schema\x18\x01 \x02(\x0b\x32\x12.RpbYokozunaSchema\"\'\n\x17RpbYokozunaSchemaGetReq\x12\x0c\n\x04name\x18\x01 \x02(\x0c\">\n\x18RpbYokozunaSchemaGetResp\x12\"\n\x06schema\x18\x01 \x02(\x0b\x32\x12.RpbYokozunaSchemaB)\n\x17\x63om.basho.riak.protobufB\x0eRiakYokozunaPB')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'riak_yokozuna_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.basho.riak.protobufB\016RiakYokozunaPB'
  _RPBYOKOZUNAINDEX._serialized_start=23
  _RPBYOKOZUNAINDEX._serialized_end=86
  _RPBYOKOZUNAINDEXGETREQ._serialized_start=88
  _RPBYOKOZUNAINDEXGETREQ._serialized_end=126
  _RPBYOKOZUNAINDEXGETRESP._serialized_start=128
  _RPBYOKOZUNAINDEXGETRESP._serialized_end=187
  _RPBYOKOZUNAINDEXPUTREQ._serialized_start=189
  _RPBYOKOZUNAINDEXPUTREQ._serialized_end=264
  _RPBYOKOZUNAINDEXDELETEREQ._serialized_start=266
  _RPBYOKOZUNAINDEXDELETEREQ._serialized_end=307
  _RPBYOKOZUNASCHEMA._serialized_start=309
  _RPBYOKOZUNASCHEMA._serialized_end=359
  _RPBYOKOZUNASCHEMAPUTREQ._serialized_start=361
  _RPBYOKOZUNASCHEMAPUTREQ._serialized_end=422
  _RPBYOKOZUNASCHEMAGETREQ._serialized_start=424
  _RPBYOKOZUNASCHEMAGETREQ._serialized_end=463
  _RPBYOKOZUNASCHEMAGETRESP._serialized_start=465
  _RPBYOKOZUNASCHEMAGETRESP._serialized_end=527
# @@protoc_insertion_point(module_scope)
